### ISSUE TITLE
download all button + meta instead?

### ISSUE THREAD

**Issue by shiraleeana** [smallmultiples/undp-vaccine-response#22]
When listing the datasets, instead of allowing each row to be a download, can we:

- [x] Have a Download data button instead (downloads everything).
- [x] Remove each individual download.
- [x] Add a Download meta data button (for the Data source + Last updated sheet).
